pipeline {
  agent {
    docker {
      image 'abhishekf5/maven-abhishek-docker-agent:v1'
      args '--network=jenkins-cicd_cicd-net -v /var/jenkins_home/.m2:/root/.m2'
    }
  }

  environment {
    DOCKER_IMAGE = "ultimate-cicd:${BUILD_NUMBER}"
  }

  stages {

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/Shobhit0398/jenkins-CICD.git'
      }
    }

    stage('Build and Test') {
      steps {
        sh 'cd spring-boot-app && mvn clean package -DskipTests'
      }
    }

    stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://sonarqube:9000"
      }
      steps {
        withCredentials([string(credentialsId: '4e0b44d2-0032-440b-9e3e-2747236d0d61', variable: 'SONAR_AUTH_TOKEN')]) {
          sh 'cd spring-boot-app && mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=http://sonarqube:9000'
        }
      }
    }

    stage('Build and Push Docker Image') {
      environment {
        DOCKER_IMAGE = "shobhitnagar/ultimate-cicd:${BUILD_NUMBER}"
      }
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-cred', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
          sh '''
            cd spring-boot-app
            echo "Building Docker image ${DOCKER_IMAGE}..."
            docker build --platform linux/amd64 -t ${DOCKER_IMAGE} .

            echo "Logging into Docker Hub..."
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

            echo "Pushing Docker image ${DOCKER_IMAGE}..."
            docker push ${DOCKER_IMAGE}
          '''
        }
      }
    }

    stage('Update Deployment File') {
      environment {
        GIT_REPO_NAME = "jenkins-CICD"
        GIT_USER_NAME = "Shobhit0398"
      }
      steps {
        withCredentials([string(credentialsId: 'e2d8810a-c7f5-44d9-8528-dad0ada6f4d9', variable: 'GITHUB_TOKEN')]) {
          sh '''
            git config user.email "shobhit9803@gmail.com"
            git config user.name "Shobhit"
            BUILD_NUMBER=${BUILD_NUMBER}
            sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" spring-boot-app-manifests/deployment.yml
            git add spring-boot-app-manifests/deployment.yml
            git commit -m "Update deployment image to version ${BUILD_NUMBER}"
            git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:main
          '''
        }
      }
    }
  }
}
